apiVersion: v1
kind: Service
metadata:
  name: model-serving-api
  namespace: picpay-ml
  labels:
    name: model-serving-api
spec:
  type: ClusterIP
  selector:
    name: model-serving-api
  ports:
    - name: http
      port: 80
      targetPort: 80