apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: picpay-ml
  labels:
    name: mongodb
spec:
  type: ClusterIP
  selector:
    name: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017