apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth
  namespace: picpay-ml
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin1234"
  MONGODB_URI: "mongodb://admin:admin1234@mongodb:27017/picpay_metadata?authSource=admin"